on:
  push:
    branches:
      - main
      
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v6
      - name: Setup project
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      # - name: Publish on npm
      #   id: publish-npm
      #   uses: JS-DevTools/npm-publish@v4
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}

      # DON'T REPLICATE: this is just experimental - you should use push: tags: - "v*" instead
      - name: Check if new version exist 
        id: check-version
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          PKG=$(npm pkg get name | tr -d '"')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          if npm view "$PKG@$VERSION" > /dev/null 2>&1; then 
            echo "Version $VERSION already exist."
            echo "outcome=skip" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
      - name: Publish on npm
        id: publish-npm
        if: steps.check-version.outputs.outcome != 'skip'
        run: |
          echo "version=$(npm pkg get version)" >> "$GITHUB_OUTPUT"
          npm publish

      - name: Notify new version via Telegram
        if: steps.publish-npm.outcome == 'success'
        run: |
          curl -s \
          -d "chat_id=${{ secrets.CHAT_ID }}" \
          -d "text=📦 <strong>${{ github.repository }}</strong>:%0ANew version published <pre>v${{ steps.publish-npm.outputs.version }}</pre>" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?parse_mode=html > /dev/null
